# Generated by Django 5.2.1 on 2025-07-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TumaGo_Server', '0002_rename_vehicle_name_drivervehicle_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_picture',
            field=models.ImageField(blank=True, null=True, upload_to='License/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='license',
            field=models.BooleanField(default=False),
        ),
    ]
